version: '3.9'

services:
  programas-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    networks:
      - sga-network

  usuarios-service:
    build:
      context: .
      dockerfile: UsuariosService/Dockerfile
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - sga-network

  inscripciones-service:
    build:
      context: .
      dockerfile: InscripcionesService/Dockerfile
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - sga-network

  inscripciones-web:
    build:
      context: .
      dockerfile: InscripcionesWeb/Dockerfile
    ports:
      - "5000:8080"
    networks:
      - sga-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

networks:
  sga-network:
    driver: bridge




